import {useMemo,useState} from "react";
import {datasource,q,useRecords,useRecordUpdate} from "@/lib/datasource";
import {Search,ShieldCheck,Mail,Clock,Building2,Users,ChevronRight,X,ExternalLink,FileText} from "lucide-react";
const ds=datasource.define({applications:"applications"});
const fields=q.select({app:"Application",university:"University",team:"Engineering Team Name",teamType:"Engineering Team Type",applicant:"Applicant Name",email:"Applicant Email",role:"Applicant Role",sponsor:"Sponsor Company",program:"Sponsorship Program",requestType:"Sponsorship Type Requested",value:"Amount / Value Requested",support:"Requested Support",why:"Why This Sponsor Is a Good Fit",project:"Team / Project Description",offer:"What the Team Can Offer Sponsor",submitted:"Submitted Date",needBy:"Need-By Date",status:"Application Status",delivery:"Email Delivery Status",recipient:"Recipient Email",website:"Team Website",deck:"Sponsorship Deck URL"});
const updateFields=q.select({status:"Application Status",delivery:"Email Delivery Status"});
const STATUS=["Draft","Submitted","Email Sent","Delivery Failed","Response Received","Approved","Rejected","Closed"];
function text(v:any){if(v==null)return "";if(typeof v==="string"||typeof v==="number")return String(v);if(Array.isArray(v))return v.map(text).filter(Boolean).join(", ");return v.label||v.name||v.value||""}
function date(v:any){const raw=typeof v==="string"?v:v?.start||v?.value;if(!raw)return "—";const d=new Date(raw);return isNaN(d.getTime())?String(raw):d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}
export default function Block(){
 const {data,status,error,refetch}=useRecords({from:ds.applications,select:fields,count:100,orderBy:q.desc("submitted")});
 const update=useRecordUpdate({from:ds.applications,fields:updateFields,onSuccess:()=>refetch()});
 const rows=data?.pages.flatMap(p=>p.items)??[];
 const [query,setQuery]=useState("");const [filter,setFilter]=useState("All");const [selected,setSelected]=useState<any>(null);
 const filtered=useMemo(()=>rows.filter((r:any)=>{const f=r.fields;const hay=[text(f.app),text(f.university),text(f.team),text(f.applicant),text(f.sponsor),text(f.email)].join(" ").toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&(filter==="All"||text(f.status)===filter)}),[rows,query,filter]);
 const counts={total:rows.length,submitted:rows.filter((r:any)=>text(r.fields.status)==="Submitted").length,sent:rows.filter((r:any)=>text(r.fields.delivery)==="Sent").length,approved:rows.filter((r:any)=>text(r.fields.status)==="Approved").length};
 const setStatus=(r:any,v:string)=>{if(!update.enabled)return;update.mutate({recordId:r.id,fields:{status:v}})};
 return <div className="min-h-screen bg-[#f5f5f7] text-[#111]"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-7 lg:px-8">
  <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-black px-3 py-1.5 text-[11px] font-semibold text-white"><ShieldCheck className="h-3.5 w-3.5"/>Moderator workspace</div><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Sponsorship applications</h1><p className="mt-3 text-sm text-black/48">Review requests, email delivery, and outcomes without touching the public directory.</p></div><a href="/admin/stats" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-xs font-semibold shadow-sm ring-1 ring-black/[.06] hover:bg-black hover:text-white">View statistics <ChevronRight className="h-4 w-4"/></a></div>
  <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Applications",counts.total,FileText],["Awaiting action",counts.submitted,Clock],["Emails delivered",counts.sent,Mail],["Approved",counts.approved,ShieldCheck]].map(([k,v,I]:any)=><div key={k} className="rounded-[24px] bg-white p-5 shadow-sm ring-1 ring-black/[.05]"><div className="flex items-center justify-between text-xs text-black/42"><span>{k}</span><I className="h-4 w-4"/></div><div className="mt-5 text-3xl font-semibold tracking-[-.04em]">{v}</div></div>)}</div>
  <div className="mt-6 rounded-[28px] bg-white p-4 shadow-sm ring-1 ring-black/[.05]"><div className="grid gap-3 lg:grid-cols-[1fr_auto]"><label className="flex h-12 items-center rounded-2xl bg-[#f5f5f7] px-4"><Search className="mr-3 h-4 w-4 text-black/30"/><input className="w-full bg-transparent text-sm outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search team, university, sponsor, applicant..."/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="h-12 rounded-2xl bg-[#f5f5f7] px-4 text-xs font-semibold"><option>All</option>{STATUS.map(x=><option key={x}>{x}</option>)}</select></div></div>
  {status==="pending"?<div className="mt-6 text-sm text-black/45">Loading applications…</div>:status==="error"?<div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{String(error?.message||"Could not load applications")}</div>:<div className="mt-6 overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-black/[.05]"><div className="hidden grid-cols-[1.25fr_1fr_.8fr_.8fr_40px] gap-4 border-b border-black/[.06] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.11em] text-black/30 lg:grid"><span>Team / sponsor</span><span>Applicant</span><span>Status</span><span>Delivery</span><span/></div>{filtered.length===0?<div className="p-10 text-center text-sm text-black/40">No matching applications.</div>:filtered.map((r:any)=>{const f=r.fields;return <button key={r.id} onClick={()=>setSelected(r)} className="grid w-full gap-3 border-b border-black/[.05] px-5 py-5 text-left transition last:border-0 hover:bg-[#f8f8fa] lg:grid-cols-[1.25fr_1fr_.8fr_.8fr_40px] lg:items-center"><div><div className="font-semibold">{text(f.team)||"Unnamed team"}</div><div className="mt-1 text-xs text-black/42">{text(f.university)} → {text(f.sponsor)||text(f.program)||"Sponsor"}</div></div><div><div className="text-sm">{text(f.applicant)||"—"}</div><div className="text-xs text-black/38">{text(f.email)}</div></div><span className="w-fit rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-semibold text-blue-700">{text(f.status)||"Unknown"}</span><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-semibold ${text(f.delivery)==="Sent"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{text(f.delivery)||"Not Sent"}</span><ChevronRight className="hidden h-4 w-4 text-black/25 lg:block"/></button>})}</div>}
 </div>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-3 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-[30px] bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-black/[.06] bg-white/92 px-6 py-5 backdrop-blur-xl"><div><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-blue-600">Application</div><h2 className="mt-1 text-xl font-semibold">{text(selected.fields.team)} → {text(selected.fields.sponsor)||"Sponsor"}</h2></div><button onClick={()=>setSelected(null)} className="grid h-9 w-9 place-items-center rounded-full bg-[#f5f5f7]"><X className="h-4 w-4"/></button></div><div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-3"><Mini k="Submitted" v={date(selected.fields.submitted)}/><Mini k="Need by" v={date(selected.fields.needBy)}/><Mini k="Requested value" v={text(selected.fields.value)||"Not specified"}/></div><Section k="Requested support" v={text(selected.fields.support)}/><Section k="Project" v={text(selected.fields.project)}/><Section k="Why this sponsor" v={text(selected.fields.why)}/><Section k="What team offers" v={text(selected.fields.offer)}/><div className="grid gap-3 sm:grid-cols-2"><Mini k="Applicant" v={`${text(selected.fields.applicant)} · ${text(selected.fields.email)}`}/><Mini k="Recipient" v={text(selected.fields.recipient)||"No verified email"}/></div><div className="rounded-[22px] bg-[#f5f5f7] p-4"><label className="text-[10px] font-semibold uppercase tracking-[.12em] text-black/35">Moderator status</label><select disabled={!update.enabled||update.status==="pending"} value={text(selected.fields.status)||"Submitted"} onChange={e=>{setStatus(selected,e.target.value);setSelected({...selected,fields:{...selected.fields,status:e.target.value}})}} className="mt-2 h-11 w-full rounded-xl bg-white px-3 text-sm font-semibold outline-none">{STATUS.map(x=><option key={x}>{x}</option>)}</select></div><div className="flex flex-wrap gap-2">{text(selected.fields.website)&&<a href={text(selected.fields.website)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-black px-4 py-2.5 text-xs font-semibold text-white">Team website <ExternalLink className="h-3.5 w-3.5"/></a>}{text(selected.fields.deck)&&<a href={text(selected.fields.deck)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#f5f5f7] px-4 py-2.5 text-xs font-semibold">Sponsorship deck <ExternalLink className="h-3.5 w-3.5"/></a>}</div></div></div></div>}
 </div>
}
function Mini({k,v}:{k:string;v:string}){return <div className="rounded-2xl bg-[#f5f5f7] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.11em] text-black/30">{k}</div><div className="mt-2 text-sm font-semibold text-black/72">{v||"—"}</div></div>}
function Section({k,v}:{k:string;v:string}){return <div><div className="text-[10px] font-semibold uppercase tracking-[.11em] text-black/30">{k}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-black/65">{v||"—"}</p></div>}
